### ISSUE TITLE
typehead and datepicker error

### ISSUE THREAD

**Issue by sothearasi** [ng-bootstrap/ng-bootstrap#1130]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
[17:29:33]  Error: Error at /home/cheasotheara/Desktop/app-contact/frontend/.tmp/node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead-window.ngfactory.ts:277:40 
[17:29:33]  Supplied parameters do not match any signature of call target. 
[17:29:33]  Error at /home/cheasotheara/Desktop/app-contact/frontend/.tmp/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-month-view.ngfactory.ts:448:40 
[17:29:33]  Supplied parameters do not match any signature of call target. 
[17:29:33]  ngc failed 
[17:29:33]  ionic-app-script task: "build" 
[17:29:33]  Error: Error 

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 2

ng-bootstrap:

Bootstrap:

**Comment by pkozlowski-opensource** [comment]
Sorry but there is no enough info for us to investigate / help here. Please follow our submission guidelines if you believe that there is a bug to be fixed on our side: https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug
