### ISSUE TITLE
Build: 'gulp demo-server' doesn't work anymore

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#1133]
After the clean install `gulp demo-server` gives the issue:

```
Error: Cannot find module 'enhanced-resolve/lib/getInnerRequest'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mokorokov/Dev/ng2/ng-bootstrap/core/node_modules/@ngtools/webpack/src/paths-plugin.js:6:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mokorokov/Dev/ng2/ng-bootstrap/core/node_modules/@ngtools/webpack/src/plugin.js:14:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mokorokov/Dev/ng2/ng-bootstrap/core/node_modules/@ngtools/webpack/src/index.js:6:10)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

Manual `npm install enhanced-resolve` fixes it:

<img width="498" alt="screen shot 2016-12-09 at 16 27 16" src="https://cloud.githubusercontent.com/assets/8074436/21054124/9c65f7ce-be2c-11e6-8b52-ffb4b1b90659.png">

Don't know what do with this for now, looks like the `@ngtools/webpack` issue?

**Comment by pkozlowski-opensource** [comment]
@mlaval could you help us with this one? 

@robwormald do we have any backward-compatibility guarantees for  `@ngtools/webpack`?
