### ISSUE TITLE
 Cannot read property 'def' of undefined

### ISSUE THREAD

**Issue by qwert789** [ng-bootstrap/ng-bootstrap#1338]
Description:
When using angular 4.0.0-rc.1, NgbTooltip doesn't work.

`Uncaught TypeError: Cannot read property 'def' of undefined
    at new DebugContext_ (https://unpkg.com/@angular/core@4.0.0-rc.1/bundles/core.umd.js:12759:32)
    at getCurrentDebugContext (https://unpkg.com/@angular/core@4.0.0-rc.1/bundles/core.umd.js:12910:16)
    at DebugRendererV2.createText (https://unpkg.com/@angular/core@4.0.0-rc.1/bundles/core.umd.js:12987:73)
    at RendererAdapter.createText (https://unpkg.com/@angular/core@4.0.0-rc.1/bundles/core.umd.js:10440:58)
    at PopupService._getContentRef (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.20/bundles/ng-bootstrap.js:416:52)
    at PopupService.open (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.20/bundles/ng-bootstrap.js:391:37)
    at NgbTooltip.open (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.20/bundles/ng-bootstrap.js:4868:50)
    at HTMLButtonElement.eval (https://unpkg.com/@angular/platform-browser@4.0.0-rc.1/bundles/platform-browser.umd.js:2992:56)
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.7/dist/zone.js:363:31)
    at Object.onInvokeTask (https://unpkg.com/@angular/core@4.0.0-rc.1/bundles/core.umd.js:3288:45)
    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.7.7/dist/zone.js:362:36)
    at Zone.runTask (https://unpkg.com/zone.js@0.7.7/dist/zone.js:166:47)
    at HTMLButtonElement.ZoneTask.invoke (https://unpkg.com/zone.js@0.7.7/dist/zone.js:416:38)`

Plunker that reproduces the issue:
http://plnkr.co/edit/qpWHYlwnABD55ufSsG0d?p=preview

Angular: 
4.0.0-rc.1

ng-bootstrap:
1.0.0-alpha.20

Bootstrap:
4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
Seems like a regression in Angular 4.0-rc.1. Interestingly it happens only in the debug mode and the error is not present when switching to the prod mode: http://plnkr.co/edit/OXLUw777IHyyAiDSCzlC?p=preview

Will follow up with the rest of the Angular team.

**Comment by pkozlowski-opensource** [comment]
I can confirm that this is a regression in 4.0.0-rc.1 - here is a minimal plunker reproducing what ng-bootstrap does in respect to tooltips: https://plnkr.co/edit/eDNXO0iNeiG1InnSvSqQ?p=preview

Seems like a combination of debug mode + calls to renderer from a listener registered through a renderer makes thing fail.

**Comment by MatteoNY** [comment]
Yes, still issue with Angular 4-rc2. Same issue, see Angular-cli stack below. 
Using boostrap 4 v1.0.0-alpha.20
@angular/cli: 1.0.0-rc.0
node: 7.6.0
os: win32 x64
@angular/common: 4.0.0-rc.2
@angular/compiler: 4.0.0-rc.2
@angular/core: 4.0.0-rc.2
@angular/forms: 4.0.0-rc.2
@angular/http: 4.0.0-rc.2
@angular/material: 2.0.0-beta.2
@angular/flex-layout: 2.0.0-rc.1
@angular/platform-browser: 4.0.0-rc.2
@angular/platform-browser-dynamic: 4.0.0-rc.2
@angular/router: 4.0.0-rc.2
@angular/cli: 1.0.0-rc.0
@angular/compiler-cli: 4.0.0-rc.2

**Comment by MatteoNY** [comment]
Initially I've found that the tooltips don't work and then when you click they will work. It appears that the def is not defined initially.

**Comment by pkozlowski-opensource** [comment]
For anyone reading / tracking this issue: it was confirmed as a bug in Angular itself (based on my issue report, see: https://github.com/angular/angular/issues/14872). The bug itself was already fixed in master branch of Angular via https://github.com/angular/angular/commit/ba4b6f58d9cae50e299ddec17ca6849f1de5b6ff and the fix will be part of the next Angular release (4.0.0-rc.3).

I'm going to close this issue here as:
* there are no actionable steps remaining (bug is in Angular and is fixed already)
* there is an easy work-around (don't use debug mode but run you app in the production mode instead).
