### ISSUE TITLE
Internal error when entering dates 10 years before given minDate

### ISSUE THREAD

**Issue by cburgmer** [ng-bootstrap/ng-bootstrap#1732]
### Bug description:

When setting `minDate`, any manually entered date before `year - 10` (with `year` the year of the given `minDate`) results in an empty date picker popup and a strack trace shown in the browser's console:

```
ERROR Error: 'maxDate' 2016-12-31 should be greater than 'minDate' 2017-1-1
    at Object.checkMinBeforeMax (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.30/bundles/ng-bootstrap.js:3613:15)
    at NgbDatepickerService._updateState (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.30/bundles/ng-bootstrap.js:1478:32)
    at NgbDatepickerService._nextState (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.30/bundles/ng-bootstrap.js:1447:29)
    at NgbDatepickerService.set [as maxDate] (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.30/bundles/ng-bootstrap.js:1391:22)
    at NgbDatepicker._setDates (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.30/bundles/ng-bootstrap.js:1683:31)
    at NgbDatepicker.ngOnInit (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.30/bundles/ng-bootstrap.js:1640:18)
    at NgbInputDatepicker.open (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.30/bundles/ng-bootstrap.js:3198:33)
    at NgbInputDatepicker.toggle (https://unpkg.com/@ng-bootstrap/ng-bootstrap@1.0.0-alpha.30/bundles/ng-bootstrap.js:3226:18)
    at Object.eval [as handleEvent] (ng:///AppModule/NgbdDatepickerPopup.ngfactory.js:372:42)
    at handleEvent (https://unpkg.com/@angular/core@4.0.3/bundles/core.umd.js:11805:138)
    at ____________________Elapsed_16851_ms__At__Mon_Aug_07_2017_12_06_53_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (https://unpkg.com/zone.js@0.8.10/dist/long-stack-trace-zone.js:109:22)
    at ZoneDelegate.scheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:394:51)
    at Object.onScheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:290:29)
    at ZoneDelegate.scheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:394:51)
    at Zone.scheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:225:43)
    at Zone.scheduleEventTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:251:25)
    at zoneAwareAddListener (https://unpkg.com/zone.js@0.8.10/dist/zone.js:1255:14)
    at HTMLButtonElement.proto.(anonymous function) [as addEventListener] (https://unpkg.com/zone.js@0.8.10/dist/zone.js:1402:20)
    at ____________________Elapsed_10_ms__At__Mon_Aug_07_2017_12_06_53_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (https://unpkg.com/zone.js@0.8.10/dist/long-stack-trace-zone.js:109:22)
    at ZoneDelegate.scheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:394:51)
    at Object.onScheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:290:29)
    at ZoneDelegate.scheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:394:51)
    at Zone.scheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:225:43)
    at Zone.scheduleMicroTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:245:25)
    at scheduleResolveOrReject (https://unpkg.com/zone.js@0.8.10/dist/zone.js:803:14)
    at resolvePromise (https://unpkg.com/zone.js@0.8.10/dist/zone.js:752:21)
    at ____________________Elapsed_2_ms__At__Mon_Aug_07_2017_12_06_53_GMT_0200__CEST_ (http://localhost)
    at Object.onScheduleTask (https://unpkg.com/zone.js@0.8.10/dist/long-stack-trace-zone.js:109:22)
    at ZoneDelegate.scheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:394:51)
    at Object.onScheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:290:29)
    at ZoneDelegate.scheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:394:51)
    at Zone.scheduleTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:225:43)
    at Zone.scheduleMicroTask (https://unpkg.com/zone.js@0.8.10/dist/zone.js:245:25)
    at scheduleResolveOrReject (https://unpkg.com/zone.js@0.8.10/dist/zone.js:803:14)
    at ZoneAwarePromise.then (https://unpkg.com/zone.js@0.8.10/dist/zone.js:892:17)
```

### Link to minimally-working plunker that reproduces the issue:

http://plnkr.co/edit/KJQYTCL0qCXBlzXmBAoq?p=preview

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: @angular/core@4.3.3

ng-bootstrap: @ng-bootstrap/ng-bootstrap@1.0.0-alpha.30

Bootstrap: n/a

**Comment by pkozlowski-opensource** [comment]
Yep, definitively something fishy going on here, thnx for reporting @cburgmer !

@maxokorokov do you think that I should skip setting of invalid values on the popup? Or rather this is something that the `NgbDatepickerService` should deal with?

**Comment by akram1905** [comment]
Any updates? plans?

**Comment by bastienmoulia** [comment]
A quick fix is to add a custom `maxDate` attribute.

Anyway we should change the way the `maxDate`is calculated when only the `minDate` is set (and vice versa).

Actually the `maxDate` is the date of today or the date set if present +10 years.

I think if a  `minDate` is set (and not `maxDate`) and this date is higher than the date of today or the date set, we should calculate `maxDate` as  `minDate` + 10 years.

And the opposite to generate `minDate` when only `maxDate`  is set.

**Comment by maxokorokov** [comment]
The proper fix would be longer... There are two things here:
- `minDate` and `maxDate` that are used for navigation. Should be completely optional. User can override them, but it will allow for "infinite" navigation  in any direction by default
- `minYear` and `maxYear` displayed for the navigation with select boxes. (-10yrs, +10yrs) from currently displayed date, unless `min/maxDate` are specified

The proper fix would be to:
- move `navigation` type handling to the `NgbDatepickerService`
- move `min/maxDate` calculation logic to the `NgbDatepickerService`
- introduce `min/maxYear` select box generation to the `NgbDatepickerService`

It should be done in several steps of course... I started with #1905, but don't have much time now unfortunately now
