### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by dimitriy-k** [ng-bootstrap/ng-bootstrap#1865]
When building SSR application with Angular CLI it crashes because of ng-bootstrap. On Angular CLI forum they the 3th party packages should be packed the right way. Are you planning to make ng-bootstrap compatible with Angular CLI? How to fix this issue?

### Bug description:
```
/opt/webapp/node_modules/@ng-bootstrap/ng-bootstrap/typeahead/typeahead.js:1
(function (exports, require, module, __filename, __dirname) { import { ComponentFactoryResolver, Directive, ElementRef, EventEmitter, forwardRef, Injector, Input, NgZone, Output, Renderer2, ViewContainerRef } from '@angular/core';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.g8tU (/opt/webapp/dist-server/main.bundle.js:1:2533521)
error Command failed with exit code 1.
```

### related issue on Angular-cli
https://github.com/angular/angular-cli/issues/7200

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 4.4.3

ng-bootstrap: 1.0.0-beta.5

Bootstrap: 4.0.0-alpha.6

**Comment by pkozlowski-opensource** [comment]
Thnx for the bug report, we are going to tackle it in #858. Closing as a duplicate.
