### ISSUE TITLE
Prefixer issue with Beta 3

### ISSUE THREAD

**Issue by vinayakvinay** [ng-bootstrap/ng-bootstrap#2070]
**Bug description:**
autoprefixer - latest version breaks the Angular build.
Works fine with beta 2 and not with beta 3.

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.1.2
ng-bootstrap: 1.0.0-beta.8
Bootstrap: 4.0.0-beta.3
### Error:

```
ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","plugins":[null,null,null,null],"sourceMap":false}!./node_modules/bootstrap/dist/css/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser major
    at error (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/browserslist/index.js:37:11)
    at Function.browserslist.checkName (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/browserslist/index.js:320:18)
    at Function.select (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/browserslist/index.js:438:37)
    at /Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/browserslist/index.js:207:41
    at Array.forEach (<anonymous>)
    at browserslist (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/browserslist/index.js:196:13)
    at Browsers.parse (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/autoprefixer/lib/browsers.js:44:14)
    at new Browsers (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/autoprefixer/lib/browsers.js:39:28)
    at loadPrefixes (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/autoprefixer/lib/autoprefixer.js:56:18)
    at plugin (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/autoprefixer/lib/autoprefixer.js:62:18)
    at LazyResult.run (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.asyncTick (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:192:32)
    at LazyResult.asyncTick (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:204:22)
    at LazyResult.asyncTick (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:204:22)
    at processing.Promise.then._this2.processed (/Users/vinayagaperumalmariyappan/Documents/1-projects/6-gp/gp-ui/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:231:20)
    at new Promise (<anonymous>)
 @ ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./src/styles.css 3:10-190
 @ ./src/styles.css
 @ multi ./src/styles.css
```

**Comment by pkozlowski-opensource** [comment]
Not sure how this is related to this library?

**Comment by vinayakvinay** [comment]
Please refer this thread.
https://github.com/angular/angular-cli/issues/9020

**Comment by bastienmoulia** [comment]
Will be fix with the next version of angular-cli: https://github.com/angular/angular-cli/pull/9023

**Comment by pkozlowski-opensource** [comment]
@vinayakvinay what you are referencing talks about a problem with Bootstrap beta.3 _CSS_ and CLI which has nothing to do with this library. As such I'm going to close it here.

Thnx for the input @bastienmoulia
