### ISSUE TITLE
Dont ship ngfactory - breaks AOT build

### ISSUE THREAD

**Issue by httpete** [ng-bootstrap/ng-bootstrap#2243]
### Bug description:

I am getting an error when I build - it is related to your shipping the ngfactory.js which is not right.

ERROR in c:/Users/peters1/bench/nwfjs/angular/dist/node_modules/@ng-bootstrap/ng-bootstrap/popover/popover.ngfactory.js
Module build failed: Error: c:\Users\peters1\bench\nwfjs\angular\dist\node_modules\@ng-bootstrap\ng-bootstrap\popover\popover.ngfactory.js is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (c:\Users\peters1\bench\nwfjs_scaffolding\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (c:\Users\peters1\bench\nwfjs_scaffolding\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
 @ ./app/main-angular.module.ngfactory.js 20:0-141
 @ ./main.ts

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:

Angular: 5.2.9
ng-bootstrap:1.0.2

you want to compile with:

    "angularCompilerOptions": {
        "genDir": "dist",
        "debug": false,
        "skipTemplateCodegen": true,
        "skipMetadataEmit": false,
        "strictMetadataEmit": true
    },

**Comment by httpete** [comment]
I found it was due to the fact that I was using npm linked (locally linked projects) and your tsconfig needs to map those.  Like this if anyone else needs:

`{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "baseUrl": "./",
    "paths": {
      "@angular/*": [
        "node_modules/@angular/*"
      ],
      "@uirouter/*": [
        "node_modules/@uirouter/*"
      ],
      "@ng-bootstrap/*": [
        "node_modules/@ng-bootstrap/*"
      ]
    },
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
`
