### ISSUE TITLE
Unstable typeahead tests

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#2290]
I've seen the following tests for the typeahead fail on several occasions:

---

<details/>
<summary>1. ngb-typeahead window open on focus and click should open on focus or click</summary>

```
Chrome 65.0.3325 (Mac OS X 10.12.6) ngb-typeahead window open on focus and click should open on focus or click FAILED
	Expected 0 to be 1, 'Search count is not correct: on first focus'.
	    at checkSearchCount (src/typeahead/typeahead.spec.ts:227:33 <- temp/typeahead/typeahead.spec.js:248:53)
	    at Object.eval (src/typeahead/typeahead.spec.ts:241:11 <- temp/typeahead/typeahead.spec.js:262:29)
	    at step (temp/typeahead/typeahead.spec.js:41:23)
	    at Object.eval [as next] (temp/typeahead/typeahead.spec.js:22:53)
	    at fulfilled (temp/typeahead/typeahead.spec.js:13:58)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:381:26)
	    at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:49:39)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:76:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:380:32)
	    at Zone.run (node_modules/zone.js/dist/zone.js:141:43)
	    at node_modules/zone.js/dist/zone.js:805:57
	    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:414:31)
	    at ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:103:39)
	    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:413:36)
	    at Zone.runTask (node_modules/zone.js/dist/zone.js:181:47)
	    at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:574:35)
	    at ZoneTask.invoke (node_modules/zone.js/dist/zone.js:480:25)
	    at timer (node_modules/zone.js/dist/zone.js:1491:29)
	Expected null not to be null.
	    at checkWindowIsOpen (src/typeahead/typeahead.spec.ts:237:77 <- temp/typeahead/typeahead.spec.js:256:95)
	    at Object.eval (src/typeahead/typeahead.spec.ts:242:11 <- temp/typeahead/typeahead.spec.js:263:29)
	    at step (temp/typeahead/typeahead.spec.js:41:23)
	    at Object.eval [as next] (temp/typeahead/typeahead.spec.js:22:53)
	    at fulfilled (temp/typeahead/typeahead.spec.js:13:58)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:381:26)
	    at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:49:39)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:76:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:380:32)
	    at Zone.run (node_modules/zone.js/dist/zone.js:141:43)
	    at node_modules/zone.js/dist/zone.js:805:57
	    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:414:31)
	    at ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:103:39)
	    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:413:36)
	    at Zone.runTask (node_modules/zone.js/dist/zone.js:181:47)
	    at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:574:35)
	    at ZoneTask.invoke (node_modules/zone.js/dist/zone.js:480:25)
	    at timer (node_modules/zone.js/dist/zone.js:1491:29)
```
</details>

---

<details/>
<summary>2. ngb-typeahead window open on focus and click should preserve value previously selected with mouse when reopening with focus then closing without selection</summary>

```
Chrome 65.0.3325 (Mac OS X 10.12.6) ngb-typeahead window open on focus and click should preserve value previously selected with mouse when reopening with focus then closing without selection FAILED
	Expected null not to be null 'Window should be opened after focusing back the input'.
	    at Object.eval (src/typeahead/typeahead.spec.ts:294:43 <- temp/typeahead/typeahead.spec.js:320:61)
	    at step (temp/typeahead/typeahead.spec.js:41:23)
	    at Object.eval [as next] (temp/typeahead/typeahead.spec.js:22:53)
	    at fulfilled (temp/typeahead/typeahead.spec.js:13:58)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:381:26)
	    at AsyncTestZoneSpec.onInvoke (node_modules/zone.js/dist/async-test.js:49:39)
	    at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:76:39)
	    at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:380:32)
	    at Zone.run (node_modules/zone.js/dist/zone.js:141:43)
	    at node_modules/zone.js/dist/zone.js:805:57
	    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:414:31)
	    at ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:103:39)
	    at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:413:36)
	    at Zone.runTask (node_modules/zone.js/dist/zone.js:181:47)
	    at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:574:35)
	    at ZoneTask.invoke (node_modules/zone.js/dist/zone.js:480:25)
	    at timer (node_modules/zone.js/dist/zone.js:1491:29)
```
</details>

---

Unfortunately I have no guaranteed reproduction scenario for this one. 
It often happened on a slow Windows machine

cc @ymeine

**Comment by pkozlowski-opensource** [comment]
Yes, saw this on my side as well. @ymeine could you please have a look? 
@maxokorokov @ymeine maybe the best approach would be to drop those as unit-tests and re-create as e2e tests as soon as we've got protractor set up?
