### ISSUE TITLE
ng build --prod fails

### ISSUE THREAD

**Issue by jthalliley** [ng-bootstrap/ng-bootstrap#2427]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
When I try to build my project with
```     ng build --prod ```
I get the following errors, stating that the ng-bootstrap package is perhaps not built correctly:

```
==> ng build --prod
Date: 2018-06-01T09:50:38.381Z                                                            
Hash: 696a8bb0b69cbf5b511c
Time: 67388ms
chunk {scripts} scripts.385b291e179030219400.bundle.js (scripts) 137 kB [initial] [rendered]
chunk {0} main.134d38ea2bc10eac84bd.bundle.js (main) 2.19 MB [initial] [rendered]
chunk {1} polyfills.c9bd3d92b786a9531262.bundle.js (polyfills) 166 kB [initial] [rendered]
chunk {2} styles.e270cced36800690ed11.bundle.css (styles) 307 kB [initial] [rendered]
chunk {3} inline.318b50c57b4eba3d437b.bundle.js (inline) 796 bytes [entry] [rendered]

ERROR in ./node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.js
Module build failed: Error: /home/jhalliley/work/my-ui/node_modules/@ng-bootstrap/ng-bootstrap/alert/alert.ngfactory.js is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/jhalliley/work/my-ui/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/home/jhalliley/work/my-ui/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
ERROR in ./node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory.js
Module build failed: Error: /home/jhalliley/work/my-ui/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker.ngfactory.js is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/jhalliley/work/my-ui/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:674:23)
    at plugin.done.then (/home/jhalliley/work/my-ui/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
```

### Link to minimally-working plunker that reproduces the issue:

You can fork a plunker from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.
Please note that we can _not_ act on bug reports without a minimal reproduction scenario in plunker. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Version of Angular, ng-bootstrap, and Bootstrap:
```
  "dependencies": {
    "@angular-devkit/core": "^0.4.2",
    "@angular-devkit/schematics": "^0.4.2",
    "@angular/animations": "^5.2.9",
    "@angular/cdk": "^5.2.4",
    "@angular/common": "^5.2.6",
    "@angular/compiler": "^5.2.6",
    "@angular/core": "^5.2.6",
    "@angular/forms": "^5.2.6",
    "@angular/http": "^5.2.6",
    "@angular/platform-browser": "^5.2.6",
    "@angular/platform-browser-dynamic": "^5.2.6",
    "@angular/router": "^5.2.6",
    "@ng-bootstrap/ng-bootstrap": "^2.0.0",
    "@schematics/package-update": "^0.3.2",
    "ag-grid": "^17.0.0",
    "ag-grid-angular": "^17.0.0",
    "ajv-keywords": "^3.1.0",
    "bootstrap": "^4.1.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.5",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "jquery-ui-dist": "^1.12.1",
    "json-server": "^0.12.2",
    "load-awesome": "^1.1.0",
    "ngx-spinner": "^1.1.0",
    "popper.js": "^1.13.0",
    "rxjs": "^5.5.7",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "^1.7.2",
```

**Comment by pkozlowski-opensource** [comment]
ng-bootstrap 2.0.0 is _only_ compatible with Angular >= 6.0.0. You should have gotten a warning from npm / yarn about incompatible versions.

You've got 2 options:
* migrate to Angular 6.x (recommended)
* use version of ng-bootstrap compatible with Angular 5.x. Latest version of ng-bootstrap compatible with Angular 6.x is `1.1.2` - check https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md

Closing as a support request.
