### ISSUE TITLE
Failing commit hook prevents all commits to ng-bootstrap

### ISSUE THREAD

**Issue by bedag-moo** [ng-bootstrap/ng-bootstrap#2660]
### Bug description:
```
$ git commit
husky > npm run -s commitmsg (node v8.11.3)

C:\dev\git-repositories\ng-bootstrap\misc\validate-commit.js:93
  var incorrectLogFile = commitMsgFile.replace('COMMIT_EDITMSG', 'logs/incorrect-commit-msgs');
                                       ^

TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (C:\dev\git-repositories\ng-bootstrap\misc\validate-commit.js:93:40)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

husky > commit-msg hook failed (add --no-verify to bypass)
```

This doesn't appear to be related to the commit message I used, because the validation scripts fails before it even finds the message.

I am now going to disable this useless script so I can get on with my PR.

**Comment by mendeza** [comment]
Did you try `--no-verify` ?

**Comment by bedag-moo** [comment]
No -- neutering the script seemed a more permanent solution. Besides, never having needed `--no-verify` before, it was not immediately clear where the option needed to be specified (git, or to the validation script directly?), and whether and how it could be specified when committing through an IDE.

**Comment by pkozlowski-opensource** [comment]
Can't reproduce it locally I'm afraid and none of the contributors bumps into it. As such you are in the best position to reproduce, investigate and fix. If you care about this item please investigate and send a PR. We can't take action on our end as we can't reproduce...

**Comment by divdavem** [comment]
Actually, I had the same issue and I did exactly the same thing: removing the hooks.
This issue seems to be reproducible on Windows only.

**Comment by divdavem** [comment]
@m-przybylski Thank you for taking the time to investigate and open a PR. 👍 
It solves the issue on my Windows machine too!

**Comment by kukac7** [comment]
this is a problem for me.

```
> git add .
> git commit -m "sry validate commit"
husky > npm run -s commitmsg (node v10.11.0)

/Users/XXX/ng-bootstrap/misc/validate-commit.js:93
  var incorrectLogFile = commitMsgFile.replace('COMMIT_EDITMSG', 'logs/incorrect-commit-msgs');
                                       ^

TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (/Users/XXX/ng-bootstrap/misc/validate-commit.js:93:40)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)

husky > commit-msg hook failed (add --no-verify to bypass)
```
I have never been able to commit properly until I have commented on the proper part of `misc/validate-commit.js`.
