### ISSUE TITLE
ng-bootstrap datepicker issue with server side angular application

### ISSUE THREAD

**Issue by akshey-jhalani** [ng-bootstrap/ng-bootstrap#2875]
I try to add ng-bootstrap package and used its datepicker but after deploying on server i am getting an error,
/usr/src/app/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-service.js:1
(function (exports, require, module, filename, dirname) { import { NgbCalendar } from './ngb-calendar';
^^^^^^

SyntaxError: Unexpected token import
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:616:28)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.Y9zK (/usr/src/app/dist-server/main.bundle.js:1:3518)

Please guide, thanks in advance

**Comment by benouat** [comment]
Hi @akshey-jhalani would you mind detailing a bit more what you are trying to achieve.
In order to help you we need some more info...

What does it mean to _use the datepicker_ ?
What does it mean to _deploy on your server_ ?
Where do you get this stack trace ?

**Comment by akshey-jhalani** [comment]
Actually, i was using ngx-bootstrap datepicker for an angular universal application. It is working fine on local but if i run it on aot it gets failed with the error message schedule of undefined and the possible solution which i found on internet was to degrade the version of bootstrap version but is there any way to fix it without degrading bootstrap version . Angular 5

Then i used a different package ng-bootstrap's datepicker it is also working locally but on aot it gets failed by this error message

 /usr/src/app/node_modules/@ng-bootstrap/ng-bootstrap/datepicker/datepicker-service.js:1
(function (exports, require, module, _filename, _dirname) { import { NgbCalendar } from './ngb-calendar';
^^^^^^

SyntaxError: Unexpected token import
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:616:28)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.Y9zK (/usr/src/app/dist-server/main.bundle.js:1:3518)

**Comment by akshey-jhalani** [comment]
@benouat

**Comment by akshey-jhalani** [comment]
@benouat or if you can tell me which datepicker is suitable enough to be used with angular 5 universal application?
Thanks in advance

**Comment by pkozlowski-opensource** [comment]
@akshey-jhalani this is likely linked to your build setup. If you are using CLI you should be good.

If you believe  that we've got a bug on our side please open a new issue with a minimal reproduce scenario (a small GitHub repo).
