### ISSUE TITLE
A bug with 4.0.2 StaticInjectorError[NgbDropdown -> NgbModalBackdrop] (lazy + SSR)

### ISSUE THREAD

**Issue by vasyliv** [ng-bootstrap/ng-bootstrap#2988]
### Bug description:
After updating from 4.0.1 to 4.0.2 got a bug, after changing back to 4.0.1 all work fine. The project has lazy loading and SSR (this error happened during Server-Side Rendering)
```
 ERROR { Error: StaticInjectorError[NgbDropdown -> NgbModalBackdrop]:

        StaticInjectorError(Platform: core)[NgbDropdown -> NgbModalBackdrop]:

          NullInjectorError: No provider for NgbModalBackdrop!

          at NullInjector.get (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:8954:23)

          at resolveToken (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:9199:28)

          at tryResolveToken (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:9143:20)

          at StaticInjector.get (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:9040:24)

          at resolveToken (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:9199:28)

          at tryResolveToken (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:9143:20)

          at StaticInjector.get (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:9040:24)

          at resolveNgModuleDep (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:21141:33)

          at NgModuleRef_.get (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:21830:20)

          at resolveDep (D:\home\site\wwwroot\ClientApp\node_modules\@angular\core\bundles\core.umd.js:22201:49)

        ngTempTokenPath: null,

        ngTokenPath:
```

### Link to minimally-working StackBlitz that reproduces the issue:

You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
7.2.2
ng-bootstrap:
4.0.2
Bootstrap:
last

**Comment by maxokorokov** [comment]
@vasyliv if you look at the [changelog for 4.0.2](https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CHANGELOG.md#402-2019-01-28) there were no changes in dropdown or modal that could cause this. I just checked the commits just in case as well.

Also this seems really fishy `NgbDropdown -> NgbModalBackdrop`, because there is really no connection between the two...

Could you try cleaning npm caches, node_modules, etc?
