### ISSUE TITLE
Popover: Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by Inexad** [ng-bootstrap/ng-bootstrap#3276]
Suddenly (Think it happened after updated to Angular 8.1 from Angular 8.0) my ng-popover started to produce a error.

When i hover my popover element the following exception is thrown:

```
core.js:9110 ERROR DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at DefaultDomRenderer2.insertBefore (http://localhost:4200/vendor.js:99270:20)
    at BaseAnimationRenderer.insertBefore (http://localhost:4200/vendor.js:96915:23)
    at nativeInsertBefore (http://localhost:4200/vendor.js:65218:18)
    at executeActionOnElementOrContainer (http://localhost:4200/vendor.js:64782:9)
    at executeActionOnNode (http://localhost:4200/vendor.js:65644:9)
    at executeActionOnView (http://localhost:4200/vendor.js:65520:9)
    at addRemoveViewFromContainer (http://localhost:4200/vendor.js:64819:9)
    at ViewContainerRef_.insert (http://localhost:4200/vendor.js:70650:17)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.js:70625:22)
    at PopupService.open (http://localhost:4200/vendor.js:120816:54)
```
I'm using the popover like this:
```
          <div class="board-item" *ngFor="let item of items"
                       [ngbPopover]="popContent"
                       triggers="mouseenter:mouseleave"
                       [popoverTitle]="popTitle">
                    Item
                    <ng-template #popTitle>Item name</ng-template>
                    <ng-template #popContent>
                     Item content
                    </ng-template>
                  </div>
```

Angular: 8.1.0
ng-bootstrap:
"@ng-bootstrap/ng-bootstrap": "^4.1.1",

**Comment by IAfanasov** [comment]
Hi @Inexad !
Support of Angular 8 will be introduced in ng-bootstrap 5, which is in beta stage now

**Comment by Inexad** [comment]
> Hi @Inexad !
> Support of Angular 8 will be introduced in ng-bootstrap 5, which is in beta stage now

Hi ! 
I just noticed that my package.json did not update the version of ng-bootstrap..
This works when using the ng-bootstrap 5.

Thanks for quick reply. 

Regards.

**Comment by wellingtonngallo** [comment]
Hello @Inexad . Here I need to use ng-bootstrap 4, so what is issue you resolve this problem for version 5?

**Comment by poddarkhushbu07** [comment]
I am facing this same error 

 "@ng-bootstrap/ng-bootstrap": "^5.3.0",

**Comment by poddarkhushbu07** [comment]
Worked after updating to bootstrap to v6
