### ISSUE TITLE
ngcc fails during postinstall when migrating to angular 9

### ISSUE THREAD

**Issue by david-bulte** [ng-bootstrap/ng-bootstrap#3622]
### Bug description:

I'm migrating to angular 9. During the migration a new postinstall script is put in place, that runs the ngcc (_ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points_).

This seems to fail on ng-bootstrap's datepicker component. Here's the error I am seeing:

```
Warning: Entry point 'ng-bootstrap' contains deep imports into 'C:/nexuzhealth-dev/moaprfrontend/moapr/node_modules/rxjs/add/operator/filter', 'C:/nexuzhealth-dev/moaprfrontend/moapr/n
ode_modules/rxjs/Observable', 'C:/nexuzhealth-dev/moaprfrontend/moapr/node_modules/rxjs/add/observable/from', 'C:/nexuzhealth-dev/moaprfrontend/moapr/node_modules/rxjs/add/operator/deb
ounceTime', 'C:/nexuzhealth-dev/moaprfrontend/moapr/node_modules/rxjs/add/operator/map', 'C:/nexuzhealth-dev/moaprfrontend/moapr/node_modules/rxjs/add/operator/mergeMap', 'C:/nexuzheal
th-dev/moaprfrontend/moapr/node_modules/rxjs/add/operator/toArray'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Compiling ng-bootstrap : module as esm5
Compiling @ng-bootstrap/ng-bootstrap : es2015 as esm2015
Error: Error on worker #2: Error: Template parse errors:
"let-" is only supported on ng-template elements. ("</b></small>\n      </th>\n    </tr>\n  </thead>\n  <tbody>\n    <template ngFor [ngForOf]=\"rows\" [ERROR ->]let-rowz=\"$implicit\"
 let-index=\"index\">\n      <tr *ngIf=\"!(datePicker.onlyCurrentMonth && rowz["): C:/nexuzhealth-dev/moaprfrontend/moapr/node_modules/ng-bootstrap/datepicker/daypicker.component.js@11
0:1658
"let-" is only supported on ng-template elements. ("h>\n    </tr>\n  </thead>\n  <tbody>\n    <template ngFor [ngForOf]=\"rows\" let-rowz=\"$implicit\" [ERROR ->]let-index=\"index\">\n
      <tr *ngIf=\"!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6]"): C:/nexuzhealth-dev/moaprfrontend/moapr/node_modules/ng-bootstrap/datepicker/daypicker.component.js@11
0:1681
    at syntaxError (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler\bundles\compiler.umd.js:2724:21)
    at htmlAstToRender3Ast (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler\bundles\compiler.umd.js:15616:19)
    at Object.parseTemplate (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler\bundles\compiler.umd.js:18448:18)
    at ComponentDecoratorHandler._parseTemplate (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:693:33)
    at ComponentDecoratorHandler._extractInlineTemplate (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:670:33)
    at ComponentDecoratorHandler.analyze (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:204:37)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:341:40)
    at analyze (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:293:58)
    at _loop_1 (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:315:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:321:35)
    at ClusterMaster.onWorkerMessage (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:158:27)
    at C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:46:95
    at ClusterMaster.<anonymous> (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:238:57)
    at step (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\tslib\tslib.js:136:27)
    at Object.next (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\tslib\tslib.js:117:57)
    at C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\tslib\tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\tslib\tslib.js:106:16)
    at EventEmitter.<anonymous> (C:\nexuzhealth-dev\moaprfrontend\moapr\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:232:32)
    at EventEmitter.emit (events.js:321:20)

```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.0.3

ng-bootstrap: 6.0.0

Bootstrap: 4.4.1

**Comment by maxokorokov** [comment]
Hey, I think you're posting an issue in the wrong repo.

This library is called `@ng-bootstrap/ng-bootstrap`, while you're using for example `.../node_modules/ng-bootstrap/datepicker/daypicker.component.js`. And obviously we don't have the `daypicker.component.js` here.

Cheers.
