### ISSUE TITLE
"let-" is only supported on ng-template elements.

### ISSUE THREAD

**Issue by danielehrhardt** [ng-bootstrap/ng-bootstrap#3661]
### Bug description:
After Updating to the latest Angular Packages. I get a build error:

```
Compiling ng-bootstrap : module as esm5
Error: Error on worker #7: Error: Template parse errors:
"let-" is only supported on ng-template elements. ("</b></small>\n      </th>\n    </tr>\n  </thead>\n  <tbody>\n    <template ngFor [ngForOf]=\"rows\" [ERROR ->]let-rowz=\"$implicit\" let-index=\"index\">\n      <tr *ngIf=\"!(datePicker.onlyCurrentMonth && rowz["): C:/Projekte/ /  /node_modules/ng-bootstrap/datepicker/daypicker.component.js@110:1658
"let-" is only supported on ng-template elements. ("h>\n    </tr>\n  </thead>\n  <tbody>\n    <template ngFor [ngForOf]=\"rows\" let-rowz=\"$implicit\" [ERROR ->]let-index=\"index\">\n      <tr *ngIf=\"!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6]"): C:/Projekte/ /  /node_modules/ng-bootstrap/datepicker/daypicker.component.js@110:1681
    at syntaxError (C:\Projekte\ \  \node_modules\@angular\compiler\bundles\compiler.umd.js:2724:21)
    at htmlAstToRender3Ast (C:\Projekte\ \  \node_modules\@angular\compiler\bundles\compiler.umd.js:15846:19)
    at Object.parseTemplate (C:\Projekte\ \  \node_modules\@angular\compiler\bundles\compiler.umd.js:18707:18)
    at ComponentDecoratorHandler._parseTemplate (C:\Projekte\ \  \node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:694:33)
    at ComponentDecoratorHandler._extractInlineTemplate (C:\Projekte\ \  \node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:671:33)
    at ComponentDecoratorHandler.analyze (C:\Projekte\ \  \node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:204:37)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (C:\Projekte\ \  \node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:341:40)
    at analyze (C:\Projekte\ \  \node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:293:58)
    at _loop_1 (C:\Projekte\ \  \node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:315:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (C:\Projekte\ \  \node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:321:35)
    at ClusterMaster.onWorkerMessage (C:\Projekte\ \  \node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:166:27)
    at C:\Projekte\ \  \node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:50:95
    at ClusterMaster.<anonymous> (C:\Projekte\ \  \node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:246:57)
    at step (C:\Projekte\ \  \node_modules\tslib\tslib.js:139:27)
    at Object.next (C:\Projekte\ \  \node_modules\tslib\tslib.js:120:57)
    at C:\Projekte\ \  \node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Projekte\ \  \node_modules\tslib\tslib.js:109:16)
    at EventEmitter.<anonymous> (C:\Projekte\ \  \node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:240:32)
    at EventEmitter.emit (events.js:321:20)
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular:
   "@angular/core": "~9.1.0",
ng-bootstrap:
 "@ng-bootstrap/ng-bootstrap": "^6.0.2",
Bootstrap:
"bootstrap": "^4.4.1",

**Comment by pkozlowski-opensource** [comment]
Wrong project - we don't have `ng-bootstrap/datepicker/daypicker.component` here - you are likely using a different package.

**Comment by rishabhjoshi31** [comment]
I am also facing the same issue, can anyone help me regarding the same?

**Comment by guillermolam** [comment]
Same problem here
``
Compiling ng-bootstrap : module as esm5
Error: Error on worker #1: Error: Template parse errors:
"let-" is only supported on ng-template elements. ("</b></small>\n      </th>\n    </tr>\n  </thead>\n  <tbody>\n    <template ngFor [ngForOf]=\"rows\" [ERROR ->]let-rowz=\"$implicit\" let-index=\"index\">\n      <tr *ngIf=\"!(datePicker.onlyCurrentMonth && rowz["): C:/Git/api-governance-tool-sdop/node_modules/ng-bootstrap/datepicker/daypicker.component.js@110:1658
"let-" is only supported on ng-template elements. ("h>\n    </tr>\n  </thead>\n  <tbody>\n    <template ngFor [ngForOf]=\"rows\" let-rowz=\"$implicit\" [ERROR ->]let-index=\"index\">\n      <tr *ngIf=\"!(datePicker.onlyCurrentMonth && rowz[0].secondary && rowz[6]"): C:/Git/api-governance-tool-sdop/node_modules/ng-bootstrap/datepicker/daypicker.component.js@110:1681
    at syntaxError (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler\bundles\compiler.umd.js:2845:21)
    at htmlAstToRender3Ast (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler\bundles\compiler.umd.js:16355:19)
    at Object.parseTemplate (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler\bundles\compiler.umd.js:19271:18)
    at ComponentDecoratorHandler._parseTemplate (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:694:33)
    at ComponentDecoratorHandler._extractInlineTemplate (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:671:33)
    at ComponentDecoratorHandler.analyze (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\component.js:204:37)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:345:40)
    at analyze (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:297:58)
    at _loop_1 (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:325:35)
    at ClusterMaster.onWorkerMessage (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:168:27)
    at C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:52:95
    at ClusterMaster.<anonymous> (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:248:57)
    at step (C:\Git\api-governance-tool-sdop\node_modules\tslib\tslib.js:139:27)
    at Object.next (C:\Git\api-governance-tool-sdop\node_modules\tslib\tslib.js:120:57)
    at C:\Git\api-governance-tool-sdop\node_modules\tslib\tslib.js:113:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Git\api-governance-tool-sdop\node_modules\tslib\tslib.js:109:16)
    at EventEmitter.<anonymous> (C:\Git\api-governance-tool-sdop\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:242:32)
    at EventEmitter.emit (events.js:210:5)
An unhandled exception occurred: NGCC failed.
See "C:\Users\x317506\AppData\Local\Temp\ng-uKiZTd\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\Windows\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! governance-apidashboard@0.0.0 start: `ng serve --proxy-config proxy.conf.json --ssl true`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the governance-apidashboard@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
``

**Comment by guillermolam** [comment]
Solved by removing  an old dependency from package.json **"ng-bootstrap": "^1.6.3",**
```
...
"@ng-bootstrap/ng-bootstrap": "^6.1.0",
"bootstrap": "^4.4.1",
## "ng-bootstrap": "^1.6.3", ## Remove this
```

**Comment by rissom** [comment]
I have the same error, but deleting the line from package.json did not work for me. Any other ideas?

**Comment by vick-elias** [comment]
> 
> 
> I have the same error, but deleting the line from package.json did not work for me. Any other ideas?

Did you run npm install after removing that dependency?

It worked for me removing it and executing npm install

**Comment by rissom** [comment]
Solved it! Unfortunately I really have no idea what I did. But I think cleaning up angular.json and package.json helped. Also checking package versions with 
> npm outdated 
and updating packages to their current version with
> npm install <packagename>@latest. 
Thanks for the help!
