### ISSUE TITLE
angular side not working Latest boostrap version 5.0 

### ISSUE THREAD

**Issue by Bhavesh-07** [ng-bootstrap/ng-bootstrap#4151]
Version Upgradion Time Show error not supported 

### Bug description:
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: theme-color-level("success", 6) is not a color.
    ╷
151 │     rgba($fill-color, 0.999999) + "' d='" + $path + "'/%3E%3C/svg%3E";
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\ngx-toastr\toastr-bs4-alert.scss 151:5  svg-factory()
  node_modules\ngx-toastr\toastr-bs4-alert.scss 159:5  @import
  src\styles.scss 22:9                                 root stylesheet
    at processResult (D:\angular-project\GitHub\ng9Template\node_modules\webpack\lib\NormalModule.js:701:19)
    at D:\angular-project\GitHub\ng9Template\node_modules\webpack\lib\NormalModule.js:807:5
    at D:\angular-project\GitHub\ng9Template\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\angular-project\GitHub\ng9Template\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (D:\angular-project\GitHub\ng9Template\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.callback (D:\angular-project\GitHub\ng9Template\node_modules\sass-loader\dist\index.js:54:7)
    at Worker.<anonymous> (D:\angular-project\GitHub\ng9Template\node_modules\@angular-devkit\build-angular\src\sass\sass-service.js:134:25)
    at Worker.emit (events.js:375:28)
    at MessagePort.<anonymous> (internal/worker.js:216:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:399:24)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 12 

ng-bootstrap: 11.0.0-beta.2

Bootstrap: 5.0

**Comment by fbasso** [comment]
Hi @Bhavesh-07, I think you logged this issue in the wrong project, as it's related to ngx-toastr (according to your trace).
