### ISSUE TITLE
NgbDatepicker breaks on server side rendering when accessing `window`

### ISSUE THREAD

**Issue by ppicom** [ng-bootstrap/ng-bootstrap#4211]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:
NgInputDatePicker tries to access the `window` object on the server side, hence throwing a TypeError.

### Link to minimally-working StackBlitz that reproduces the issue:
As the issue involves server side rendering I'm not sure how to reproduce it in a StackBlitz, but the logs have the detailed location on where in the code this is happening.

```
ReferenceError: window is not defined
    at Object.getAllStyles (/app/dist/gh-angular/server/main.js:1:428526)
    at Object.getStyle (/app/dist/gh-angular/server/main.js:1:428601)
    at Object.position (/app/dist/gh-angular/server/main.js:1:429126)
    at Object.positionElements (/app/dist/gh-angular/server/main.js:1:430900)
    at positionElements (/app/dist/gh-angular/server/main.js:1:433769)
    at NgbInputDatepicker._updatePopupPosition (/app/dist/gh-angular/server/main.js:1:442657)
    at /app/dist/gh-angular/server/main.js:1:437642
    at SafeSubscriber.schedulerFn [as _next] (/app/dist/gh-angular/server/main.js:1:4474855)
    at SafeSubscriber.__tryOrUnsub (/app/dist/gh-angular/server/main.js:1:1686779)
    at SafeSubscriber.next (/app/dist/gh-angular/server/main.js:1:1685478)
ReferenceError: window is not defined
    at Object.getAllStyles (/app/dist/gh-angular/server/main.js:1:428526)
    at Object.getStyle (/app/dist/gh-angular/server/main.js:1:428601)
    at Object.position (/app/dist/gh-angular/server/main.js:1:429126)
    at Object.positionElements (/app/dist/gh-angular/server/main.js:1:430900)
    at positionElements (/app/dist/gh-angular/server/main.js:1:433769)
    at NgbInputDatepicker._updatePopupPosition (/app/dist/gh-angular/server/main.js:1:442657)
    at /app/dist/gh-angular/server/main.js:1:437642
    at SafeSubscriber.schedulerFn [as _next] (/app/dist/gh-angular/server/main.js:1:4474855)
    at SafeSubscriber.__tryOrUnsub (/app/dist/gh-angular/server/main.js:1:1686779)
    at SafeSubscriber.next (/app/dist/gh-angular/server/main.js:1:1685478)
ReferenceError: window is not defined
    at Object.getAllStyles (/app/dist/gh-angular/server/main.js:1:428526)
    at Object.getStyle (/app/dist/gh-angular/server/main.js:1:428601)
    at Object.position (/app/dist/gh-angular/server/main.js:1:429126)
    at Object.positionElements (/app/dist/gh-angular/server/main.js:1:430900)
    at positionElements (/app/dist/gh-angular/server/main.js:1:433769)
    at NgbInputDatepicker._updatePopupPosition (/app/dist/gh-angular/server/main.js:1:442657)
    at /app/dist/gh-angular/server/main.js:1:437642
    at SafeSubscriber.schedulerFn [as _next] (/app/dist/gh-angular/server/main.js:1:4474855)
    at SafeSubscriber.__tryOrUnsub (/app/dist/gh-angular/server/main.js:1:1686779)
    at SafeSubscriber.next (/app/dist/gh-angular/server/main.js:1:1685478)
```
You can fork a StackBlitz from one of our [demos](https://ng-bootstrap.github.io/#/components) and use it as a starting point.

Please note that we can _not_ act on bug reports without a _minimal_ reproduction scenario in a StackBlitz. Here is why:
https://github.com/ng-bootstrap/ng-bootstrap#you-think-youve-found-a-bug

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 9.1.14

ng-bootstrap: 6.2.0

Bootstrap: 4.6.0

**Comment by maxokorokov** [comment]
See https://github.com/ng-bootstrap/ng-bootstrap/pull/4212#pullrequestreview-888521233
