### ISSUE TITLE
Offcanvas: Responsive and Static/Disbled backdrop not working in combination

### ISSUE THREAD

**Issue by artur-grigoryan-cgn** [ng-bootstrap/ng-bootstrap#4372]
Please remember, the issues forum is __NOT__ for support requests. It is for bugs and feature requests only.
Please read https://github.com/ng-bootstrap/ng-bootstrap/blob/master/CONTRIBUTING.md and search
existing issues (both open and closed) prior to opening any new issue and ensure you follow the instructions therein.

### Bug description:

If i try to use `.offcanvas-lg` and  `data-bs-backdrop="false"` or `data-bs-backdrop="static"` together it throws the exception:

_offcanvas.js:179 Uncaught TypeError: Cannot read properties of undefined (reading 'backdrop')
    at Bi._initializeBackDrop (offcanvas.js:179:44)
    at new Bi (offcanvas.js:71:27)
    at Bi.getOrCreateInstance (base-component.js:65:41)
    at HTMLButtonElement.<anonymous> (component-functions.js:25:32)
    at HTMLDocument.n (event-handler.js:118:19)_

### Link to minimally-working StackBlitz that reproduces the issue:

https://codepen.io/haki_1024/pen/rNdrOYw

### Versions of Angular, ng-bootstrap and Bootstrap:

Bootstrap: 5.2.0

**Comment by artur-grigoryan-cgn** [comment]
Solved it. 
data-bs-target was missing in your documentation.
