### ISSUE TITLE
ERROR TypeError: componentFactory.create is not a function at ViewContainerRef.createComponent

### ISSUE THREAD

**Issue by xokaer** [ng-bootstrap/ng-bootstrap#4476]
![image](https://user-images.githubusercontent.com/105218396/219784118-7cae3fa4-0125-45e4-a1ba-f67e14f363e7.png)
 when i am create a survey-core in angular 12 

What is the solution ?

**Comment by jnizet** [comment]
Does this have anything to do with ng-bootstrap? If you have an issue with SurveyJS, here is not the right place to ask.

**Comment by xokaer** [comment]
Hello my tas is response this error when i create surveyon angular 12

core.js:6498 ERROR TypeError: componentFactory.create is not a function
    at ViewContainerRef.createComponent (core.js:23191:1)
    at AngularComponentFactory.create (survey-angular-ui.mjs:181:29)
    at DynamicComponentDirective.createComponent
(survey-angular-ui.mjs:205:71)
    at DynamicComponentDirective.ngOnChanges (survey-angular-ui.mjs:196:18)
    at
DynamicComponentDirective.rememberChangeHistoryAndInvokeOnChangesHook
(core.js:1510:1)
    at callHook (core.js:2548:1)
    at callHooks (core.js:2507:1)
    at executeInitAndCheckHooks (core.js:2458:1)
    at refreshView (core.js:9499:1)
    at refreshEmbeddedViews (core.js:10609:1)

**Comment by jnizet** [comment]
Closing, since this appears to be an issue with SurveyJS, and not with ng-bootstrap.

**Comment by vunb** [comment]
You should check the version of ng corresponding to Angular. For example: `Angular 12` => `ng-bootstrap@10.x.x`

That is my case and it's works!
