### ISSUE TITLE
ERROR NullInjectorError: R3InjectorError(AppModule)[NgbDropdown -> NgbDropdown]:    NullInjectorError: No provider for NgbDropdown

### ISSUE THREAD

**Issue by lelelethu** [ng-bootstrap/ng-bootstrap#4691]
When I use angular 15, everything is fine.
When I upgrade angular to 17.3.5, and the latest bootstrap, the following error occurs. Please help me!

### Bug description:
ERROR NullInjectorError: R3InjectorError(AppModule)[NgbDropdown -> NgbDropdown]: 
  NullInjectorError: No provider for NgbDropdown!
    at NullInjector.get (core.mjs:1654:27)
    at R3Injector.get (core.mjs:3093:33)
    at R3Injector.get (core.mjs:3093:33)
    at ChainedInjector.get (core.mjs:15723:36)
    at lookupTokenUsingModuleInjector (core.mjs:5730:39)
    at getOrCreateInjectable (core.mjs:5778:12)
    at ɵɵdirectiveInject (core.mjs:11050:19)
    at ɵɵinject (core.mjs:1106:60)
    at inject (core.mjs:1192:12)
    at new NgbDropdownAnchor (ng-bootstrap.mjs:6290:31)

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 17.3.5

ng-bootstrap: 16.0.0

####
`<div ngbDropdown>
						<i class="fa-regular fa-file-lines fa-xl"></i>
						<a class="menumain btn" ngbDropdownToggle>{{ 'menu.text' | transloco }}</a>
						<div ngbDropdownMenu aria-labelledby="dropdownText">
							<a ngbDropdownItem routerLink="comparetext" routerLinkActive="router-link-active">{{ 'text.compareText.title' | transloco }}</a>
							<a ngbDropdownItem routerLink="texttohex" routerLinkActive="router-link-active">{{ 'text.textToHex.title' | transloco }}</a>
							<a ngbDropdownItem routerLink="texttobase64" routerLinkActive="router-link-active">
								{{ 'text.textToBase64.title' | transloco }}
							</a>
						</div>
					</div>`

**Comment by jnizet** [comment]
Hi @lelelethu.

You probably forgot to import the NgbDropdown directive.
If you really think this is a bug in ng-bootstrap, then provide a complete minimal reproduction as a stackblitz.

I doubt this is a bug in ng-bootstrap though. So you should be seeking for help elsewhere, like the Angular Discord or Stackoverflow.

**Comment by maxokorokov** [comment]
Closing as no response, please reopen if necessary.

**Comment by harshpatel147** [comment]
I previously encountered a NullInjectorError when using NgbDropdown in my Angular 17.3 standalone project. To investigate further, I created a [StackBlitz demo](https://stackblitz.com/edit/stackblitz-starters-lfdwncpg?file=src%2Fapp%2Fapp.component.html), but the error didn’t occur there — the dropdown worked as expected.

After that, I ran a fresh npm install and restarted the Angular server locally. The error also disappeared from my local environment.

It seems the issue was likely related to a temporary inconsistency in my local node_modules or dependency tree, rather than a problem with NgbDropdown itself.

Just sharing this in case anyone else runs into a similar issue — a clean install and restart might resolve it.

@maxokorokov  I think this issue can be closed. In my case, the error was resolved after reinstalling dependencies (npm install) and restarting the Angular server. It seems to have been related to a local setup issue rather than a problem with NgbDropdown. Thanks!
