### ISSUE TITLE
Zoneless change detection support

### ISSUE THREAD

**Issue by maxokorokov** [ng-bootstrap/ng-bootstrap#4709]
This is an aggregate issue to track zoneless support with `provideExperimentalZonelessChangeDetection()` in apps using ng-bootstrap.

Please open separate issues for specific use cases, we'll reference them here.
And keep in mind this is still considered "experimental".

**Comment by maxokorokov** [comment]
Demo site uses zoneless now → #4728

**Comment by sysmat** [comment]
is this lib zonless ready?

**Comment by ct-dixit** [comment]
is this lib zonless ready?

**Comment by immotus** [comment]
> is this lib zonless ready?

Yes, it is. Tested with Angular 19, zoneless, with partial hydration. Also, apparently their demo website uses zoneless, too.

**Comment by sysmat** [comment]
when I use ng 19 & "@ng-bootstrap/ng-bootstrap": "^18.0.0 & ngb-toast I get error

```
RuntimeError: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'bg-success text-bg-success'. Expression location: _ToastsContainerComponent component It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook? Find more at https://angular.dev/errors/NG0100
    at throwErrorIfNoChangesMode (core.mjs:11268:9)
    at bindingUpdated (core.mjs:19869:9)
    at checkStylingMap (core.mjs:25579:30)
    at ɵɵclassMap (core.mjs:25523:3)
    at ToastsContainerComponent_For_1_Template 
    at executeTemplate (core.mjs:12051:5)
    at refreshView (core.mjs:14322:7)
    at detectChangesInView (core.mjs:14531:5)
    at detectChangesInViewIfAttached (core.mjs:14493:3)
    at detectChangesInEmbeddedViews (core.mjs:14453:7)
```

**Comment by sysmat** [comment]
it seams if I use modal and in modal call toast I get this error `RuntimeError: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'bg-success text-bg-success'. Expression location: _ToastsContainerComponent component It seems like the view has been`

**Comment by hakimio** [comment]
@sysmat 
The error you are getting is not related to `zoneless` mode. Also, it's perfectly fine to use `zone.run()` and `zone.runOutsideAngular()` in `zoneless` ready UI libraries. You are only not allowed to use `onMicrotaskEmpty()`, `onUnstable()`, `onStable` and `isStable()` zone functions.
[More info](https://angular.dev/guide/experimental/zoneless)

**Comment by sysmat** [comment]
@hakimio hm I'm just using this lib

1.   provideExperimentalZonelessChangeDetection()
2. readonly #modalService = inject(NgbModal);
3. opening the modal `const modalRef = this.#modalService.open(ConfirmModalComponent);`
4. on confirm calling #toastService  https://ng-bootstrap.github.io/#/components/toast/examples#howto-global

```typescript
modalRef.result.then(
      () => {
        this.#toastService.info({
          type: 'text',
          title: 'toast from modal',
          text: 'This will hide when clicked. zzzzznas ščćdsasdadsd',
          autohide: false,
        });     
      },
      () => {
        
      }
    );
```

**Comment by sysmat** [comment]
- `export declare class NgbToast implements AfterContentInit, OnChanges`  this lib is far for zoneless 
- If I use ngx-toastr lib it works fine

**Comment by hakimio** [comment]
@sysmat [The NG0100 error](https://angular.dev/errors/NG0100) can be caused by the library or your code, reproduction is needed to be sure. I am only saying that it can happen in both - zoneful and zoneless apps and it's not directly related to zoneless mode. You should open a new issue if you think it's caused by the UI library instead of complaining here.

**Comment by sysmat** [comment]
@hakimio complining, it is use case for zonless, yeah I hope have time to post reproduction

**Comment by sysmat** [comment]
@hakimio reproduction: https://stackblitz.com/edit/stackblitz-starters-rgiik8r6?file=demo%2Fsrc%2Fapp%2Fapp.component.ts

**Comment by quentinderoubaix** [comment]
We have been tracking issues with zonless for a while now. Demo size has been running in zoneless since version 17.0.1.

We will consider ng-bootstrap 20 our official zoneless support and patch if any issue is found.
For tests, you can track issue #4879
