### ISSUE TITLE
NG0911: View has already been destroyed.

### ISSUE THREAD

**Issue by kaisnb** [ng-bootstrap/ng-bootstrap#4772]
### Bug description:

I've get a lot of `NG0911: View has already been destroyed.` exceptions coming from ng-bootstrap. E.g. I use a `ngbTooltip` with `openDelay` on a button that triggers navigation. If the button is clicked before the tooltip has opened, the injection context is destroyed and the [`afterNextRender` call](https://github.com/ng-bootstrap/ng-bootstrap/commit/14d5eba98d6bd527a25c05edd8fbc4eb3d96ee35#diff-28ccd83b355ab246ef912a623bf11e5c61fea00adbf8fe0054586f875adb75d4R57) causes this issue. Of course I could just remove the delay but generally I think error should somehow be prevented or swallowed. It was maybe introduced in [this commit](https://github.com/ng-bootstrap/ng-bootstrap/commit/14d5eba98d6bd527a25c05edd8fbc4eb3d96ee35#diff-28ccd83b355ab246ef912a623bf11e5c61fea00adbf8fe0054586f875adb75d4R57).

### Stacktrace

```
RuntimeError: NG0911: View has already been destroyed.
    at storeLViewOnDestroy (core.mjs:4231:11)
    at NodeInjectorDestroyRef.onDestroy (core.mjs:6471:5)
    at new AfterRenderSequence (core.mjs:19076:44)
    at afterRenderImpl (core.mjs:19125:20)
    at afterNextRender (core.mjs:19104:10)
    at PopupService.open (ng-bootstrap.mjs:9061:5)
    at _NgbTooltip.open (ng-bootstrap.mjs:15430:30)
    at ng-bootstrap.mjs:11922:56
    at sentryWrapped (helpers.js:81:17)
    at timer (zone.js:1752:27)
    at _ZoneDelegate.invokeTask (zone.js:364:171)
    at core.mjs:6714:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:6714:30)
    at _ZoneDelegate.invokeTask (zone.js:364:54)
    at Object.onInvokeTask (core.mjs:7034:25)
    at _ZoneDelegate.invokeTask (zone.js:364:54)
    at ZoneImpl.runTask (zone.js:163:37)
    at invokeTask (zone.js:441:26)
    at ZoneTask.invoke (zone.js:430:38)
    at data.args.<computed> (zone.js:1719:26)
```

### Versions of Angular, ng-bootstrap and Bootstrap:

Angular: 18.2.7

ng-bootstrap: 17.0.1

Bootstrap: 5.3.3

**Comment by kaisnb** [comment]
I guess it would be enough to check in the `NgbTooltip#open` method if the view is destroyed yet or not.

**Comment by madhunalagarla** [comment]
Even I am getting the same issue, Seems like the issue have been introduced as part of "17.0.1" version.

![image](https://github.com/user-attachments/assets/25fbd0e4-017a-4758-a68d-7c380132a00c)

![image](https://github.com/user-attachments/assets/85a10688-d219-4bea-837d-2a4e28752b32)

I've tried few workaround to mitigate the issue but It didn't work. Hoping the team aware of this issue and they are working on it.

**Comment by phillipwildhirt** [comment]
+1

**Comment by unignostik** [comment]
Getting this in the same scenario described in original posting - using a `ngbTooltip `with `openDelay`
![image](https://github.com/user-attachments/assets/049dbb20-e056-4f05-bf93-214fb1aa2319)

Angular 18.2.7

**Comment by Cubelaster** [comment]
Same issue. 
Ngb tries to handle (open or close) already destroyed component. 
Seems like internal Ngb bug since it never happened on previous versions.
I recently upgraded everything from 14 to 17 and later 18 and it started appearing. 
Doesn't break the app or anything but still dies the console in red.

**Comment by DanielWojciechowskiLingaro** [comment]
The same issue on my side. Angular 18.2.7, ng-bootstrap 17.0.1
![image](https://github.com/user-attachments/assets/da1f29e1-4804-4aca-ae50-8168cbe58dfd)

**Comment by Chityalaakhil** [comment]
Adding this check in NgbTooltip#open is fixing the issue but doesn't look like a better approach. Any suggestions?

![image](https://github.com/user-attachments/assets/3fe61a0b-6d0c-4c8b-a5fe-6864727096f3)

**Comment by GeaReinink** [comment]
No news/update on this yet?

**Comment by sschoeb** [comment]
I do not have the issue with 17.0.0 but with 17.0.1. So for me downgrading to 17.0.0 fixes the problem for now.

**Comment by Nness** [comment]
`openDelay` for tooltip or popover has issue since v16. #4657

**Comment by zarkosusnjar-adacta** [comment]
Confirming the issue NG0911 in onDestroy, in tooltip component v18.0.0, Angular 19.1.5.
