### ISSUE TITLE
publish 1.0.0-alpha.2

### ISSUE THREAD

**Issue by tsm91** [ng-bootstrap/ng-bootstrap#561]
Publish `alpha.2` to npm, or is it being hold back on purpose?

Btw, its also problematic to install it form git `npm i https://github.com/ng-bootstrap/ng-bootstrap` because of the install script.

```sh
chat-fe $ npm i https://github.com/ng-bootstrap/ng-bootstrap

> ng-bootstrap@1.0.0-alpha.2 install /Users/tsm/Sites/__projects/chat-fe/node_modules/ng-bootstrap
> node misc/validate-commit.install.js

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.git/hooks/commit-msg'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.<anonymous> (/Users/tsm/Sites/__projects/chat-fe/node_modules/ng-bootstrap/misc/validate-commit.install.js:10:6)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
```

**Comment by pkozlowski-opensource** [comment]
Releasing today, in few hours.

**Comment by pkozlowski-opensource** [comment]
FYI alpha.2 was just released. It is on npm and the updated demo site is up.
