### ISSUE TITLE
Modal component as content in lazyloadModule 

### ISSUE THREAD

**Issue by gordanyang** [ng-bootstrap/ng-bootstrap#895]
ProductModule is a lazy loaded module ,i add "declarations:[ AddProduct]"  and add "entryComponents: [AddProduct]".but there has  some error in console.
in AppModule it works;
```
@NgModule({
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    NgaModule,
    routing,
    NgbModule,
    Angular2DataTableModule,
    SelectModule
  ],
  declarations: [
    AddProduct,
    Prodmgr,
    Product
  ],
  providers: [
  ],
  entryComponents: [AddProduct]
})
export default class ProductModule {
}
```

```
[] [Array[0]]
error_handler.js:48 EXCEPTION: Error in ./Prodmgr class Prodmgr - inline template:1:48 caused by: No component factory found for AddProductErrorHandler.handleError @ error_handler.js:48next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
error_handler.js:50 ORIGINAL EXCEPTION: No component factory found for AddProductErrorHandler.handleError @ error_handler.js:50next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
error_handler.js:53 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:53next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
error_handler.js:54 Error: No component factory found for AddProduct
    at NoComponentFactoryError.Error (native)
    at NoComponentFactoryError.BaseError [as constructor] (http://localhost:3000/vendor.bundle.js:31024:34)
    at new NoComponentFactoryError (http://localhost:3000/vendor.bundle.js:31782:16)
    at _NullComponentFactoryResolver.resolveComponentFactory (http://localhost:3000/vendor.bundle.js:31791:15)
    at NgModuleInjector.CodegenComponentFactoryResolver.resolveComponentFactory (http://localhost:3000/vendor.bundle.js:31816:35)
    at NgbModalContainer._getContentRef (http://localhost:3000/main.bundle.js:2213:69)
    at NgbModalContainer.open (http://localhost:3000/main.bundle.js:2181:31)
    at NgbModalStack.open (http://localhost:3000/main.bundle.js:2358:36)
    at NgbModal.open (http://localhost:3000/main.bundle.js:2478:33)
    at Prodmgr.addProduct (http://localhost:3000/2.chunk.js:2629:27)
    at DebugAppView._View_Prodmgr0._handle_click_2_0 (Prodmgr.ngfactory.js:284:28)
    at http://localhost:3000/vendor.bundle.js:33168:24
    at http://localhost:3000/vendor.bundle.js:46803:36
    at http://localhost:3000/vendor.bundle.js:46905:111
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15269:28)
    at Object.onInvoke (http://localhost:3000/vendor.bundle.js:36115:37)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:15268:34)
    at Zone.runGuarded (http://localhost:3000/polyfills.bundle.js:15176:47)
    at NgZone.runGuarded (http://localhost:3000/vendor.bundle.js:36010:69)
    at HTMLButtonElement.outsideHandler (http://localhost:3000/vendor.bundle.js:46905:79)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:15302:37)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:15202:47)
    at HTMLButtonElement.ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:15370:33)ErrorHandler.handleError @ error_handler.js:54next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
error_handler.js:57 ERROR CONTEXT:ErrorHandler.handleError @ error_handler.js:57next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
error_handler.js:58 DebugContext {_view: _View_Prodmgr0, _nodeIndex: 2, _tplRow: 1, _tplCol: 48}ErrorHandler.handleError @ error_handler.js:58next @ application_ref.js:298schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:81NgZone.triggerError @ ng_zone.js:280onHandleError @ ng_zone.js:259ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113NgZone.runGuarded @ ng_zone.js:133outsideHandler @ dom_events.js:30ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
zone.js:140 Uncaught Error: Error in ./Prodmgr class Prodmgr - inline template:1:48 caused by: No component factory found for AddProductZone.runTask @ zone.js:140ZoneTask.invoke @ zone.js:304

```

angular: 2.1.0
ng-bootstrap: 1.0.0.alpha.8

**Comment by Kamshak** [comment]
How did you solve this?

**Comment by Kamshak** [comment]
Nevermind, just saw this: https://github.com/ng-bootstrap/ng-bootstrap/pull/974
