### ISSUE TITLE
Documentation: collapse/markup error at Self-Closing Alert

### ISSUE THREAD

**Issue by seveves** [ng-bootstrap/ng-bootstrap#961]
### Bug description:
Documentation shows error when collapsing the code at "Self-Closing Alert".
(link: [https://ng-bootstrap.github.io/#/components/alert])

This error message is shown in the browser log:
```
EXCEPTION: Cannot read property 'markup' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'markup' of undefined
    at t._View_n2.detectChangesInternal (n.ngfactory.js:277:87)
    at t.detectChanges (https://ng-bootstrap.github.io/js/vendor.615300bddb638ab05dd5.js:4:15495)
    at t.detectContentChildrenChanges (https://ng-bootstrap.github.io/js/vendor.615300bddb638ab05dd5.js:4:15877)
    at t._View_n4.detectChangesInternal (n.ngfactory.js:286:8)
    at t.detectChanges (https://ng-bootstrap.github.io/js/vendor.615300bddb638ab05dd5.js:4:15495)
    at t.detectContentChildrenChanges (https://ng-bootstrap.github.io/js/vendor.615300bddb638ab05dd5.js:4:15877)
    at t._View_n3.detectChangesInternal (n.ngfactory.js:235:8)
    at t.detectChanges (https://ng-bootstrap.github.io/js/vendor.615300bddb638ab05dd5.js:4:15495)
    at t.detectContentChildrenChanges (https://ng-bootstrap.github.io/js/vendor.615300bddb638ab05dd5.js:4:15877)
    at t._View_n0.detectChangesInternal (n.ngfactory.js:82:8)
Uncaught TypeError: Cannot read property 'markup' of undefined

```

**Comment by pkozlowski-opensource** [comment]
Thnx for reporting, it is indeed a pb on our demo site. Sent a PR to correct this.

**Comment by curtisrutland** [comment]
Similar issue on the [tabs](https://ng-bootstrap.github.io/#/components/tabs) page; expanding the code for most of the samples results in an error `Unable to get property 'markup' of undefined or null reference`.

**Comment by pkozlowski-opensource** [comment]
Thnx @curtisrutland - I've updated my PR #964 (plus went over the whole documentation site and found one more pb in accordion - this is fixed as well).
